### ISSUE TITLE
Fix typos in issue on talent management

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-perspectives#1]
Eagle-eyed reader @RonMcFarland has submitted the following typos in need of fixing:

- [x] Typo (page 16, right, middle):  "And you’ll need to do (it) quickly, because the war for talent could cause an outflow of people from your organization if you don’t."
- [x] Typo (page 17, left second paragraph): If your organization has establishing (established) systems for building effective connections between senior leaders and emerging leadership talent during the hybrid phase (and both are willing to learn from each other) you’ll see the possibility for real change.
- [x] Typo (page 20, right, second paragraph):  It may be confirmation (of) the fact that you’re facilitating an effective organizational transformation—and the new rules, norms, preferences, and standards are becoming more clear and obvious to everyone.
- [x] Typo (page 21, left, second to last paragraph):  "This means developing organizational flow; leaders must be able to follow their passions and interests, and the degree to which your organization allows this will (determine) whether and how quickly you achieve the kind of organizational balance I mentioned earlier."

**Comment by semioticrobotic** [comment]
I've addressed these typos as part of an upcoming revision. Thanks, @RonMcFarland!

**Comment by RonMcFarland** [comment]
Very good.  Thanks
