### ISSUE TITLE
Add an issue on social impact-focused open organizations

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/open-perspectives#4]
Ambassadors @LauraHilliger and @Hleson are brainstorming their open perspective on humanitarian organizations. Making a note here so we can discuss and track the work.

**Comment by LauraHilliger** [comment]
In [Open is an Extreme](https://leanpub.com/extremeopen), I pulled together articles of a thematic and wrote intros to the sections. Here are some articles I've penned that might be appropriate for such a curative project. I have loads more already written, so I guess we just need to have a think about the arc we want to take people through. 

* During a pandemic: https://opensource.com/open-organization/20/8/power-open-source-during-pandemic
* the GP series: https://opensource.com/tags/open-organization-greenpeace
* power dynamics/fear: https://opensource.com/open-organization/19/3/open-secrets-bystander-effect
https://opensource.com/open-organization/18/3/empowerment-and-leadership
https://opensource.com/open-organization/17/8/what-to-do-when-nobody-participates
https://opensource.com/open-organization/17/5/team-impostor-syndrome
*storytelling https://opensource.com/open-organization/17/1/what-storytellers-can-teach-open-leaders

**Comment by semioticrobotic** [comment]
Great! Thanks, @LauraHilliger. I'm happy to help compile all these into a cohesive manuscript after you and @Hleson have had the opportunity to discuss your narrative arc. Feel free, too, to change the name of this GitHub issue so it better reflects your intention with/for the perspective.

Thanks for getting this rolling!

**Comment by Hleson** [comment]
HI everyone. I have a product deadline on Friday.

I can talk next week. Suggest a date and time? Not Monday

heather
Heather Leson
***@***.***
Twitter/skype: HeatherLeson
Blog: textontechs.com

**Comment by semioticrobotic** [comment]
I'll be out of the office for an extended period encompassing the Thanksgiving holiday in the U.S. But don't let me be a blocker for your brainstorming. I will catch up gladly and speedily on return.

**Comment by semioticrobotic** [comment]
Updating this issue to note that I met with @LauraHilliger and @Hleson recently and can confirm they are writing an issue on this topic!

**Comment by LauraHilliger** [comment]
Hello my dears!

I've run out of steam now, but just spent the last couple of hours on our paper. Thank you @Hleson so much for our meeting this week, your allyship is why this is happening!! I feel like we're getting there finally. I've tried to paint an arc and not be repetitive, while also trying to focus on some very real advice. I am VERY interested in your thoughts, so whenever you have time have a read, use the suggestion/commenting feature. 

@semioticrobotic this is more of an FYI "we're on it" for you, but also, this really feels like it could be an online resource on our new site (for which I haven't had time for, sorry!)

**Comment by semioticrobotic** [comment]
Awesome! Great to see this moving forward, @LauraHilliger. I did a little editing and overall tidying, just to keep things moving forward for you. I see @Hleson also added a few new comments.

**Comment by LauraHilliger** [comment]
@semioticrobotic I think we are ready for you 🥳 @Hleson and I have been meeting and discussing and writing regularly. Our draft is complete. We have NOT done the executive summary at all because we thought maybe fresh eyes would help there. Please do feel free to comment, correct, make suggestions all the things you are most excellent at. And we would love to hear your honest feedback!! Whenever you have some time: https://docs.google.com/document/d/1A8Ee93En1jLluY8JCsQ-trdAfgY4vnJemXJzl8OaS3c/edit#

@Hleson for you to check/add: the Audience stuff at the beginning we talked about, and the Take Heart piece at the end. And anything yellow in between. Also need a bio for you!

**Comment by semioticrobotic** [comment]
This is excellent news! Checking on the status of this work was on my list for tomorrow, so we are apparently right on the schedule we never actually established or coordinated. :tada: 

I'm eager to read and will leave my usual take-or-leave suggestions! Thanks, @LauraHilliger and @Hleson!

**Comment by semioticrobotic** [comment]
Okay, now I've finished everything but the `Setting strategy` section, which I will do my best to knock out by Friday. Meanwhile, take a look and see what you think of the rest.

**Comment by semioticrobotic** [comment]
Great progress on revisions, team. I'm impressed. I have just a few more outstanding comments and questions I'll want to resolve before we can go to production. Have a look when you get a chance, and feel free to reach out if you think it'll be easier to discuss these on a call.

**Comment by LauraHilliger** [comment]
trying to push this over the line!

**Comment by semioticrobotic** [comment]
I am attending [FOSS Backstage](https://foss-backstage.de/) sessions today (remotely, sadly) but will make time between presentations to review.

**Comment by LauraHilliger** [comment]
No rush @semioticrobotic - i meant to say THANK YOU too!!

**Comment by semioticrobotic** [comment]
Roger that! Thanks so much, @LauraHilliger.

I'm formatting the work now. This takers a little time (mostly the conversion of hyperlinks to footnotes), but I should be able to do it in fairly short order. Meanwhile, you are welcome to review and circulate as you see fit.

Please just use [this working document as the canonical version](https://notes.theopenorganization.org/619cg-l7RlqQBKHpivYWfw#) going forward. Thanks!

**Comment by semioticrobotic** [comment]
Just a note that footnotes are now complete and the piece is ready for final review. Meanwhile, I will be:

- outlining an executive summary
- editing @Hleson's bio

Happy to help in other ways you see fit, too.

**Comment by semioticrobotic** [comment]
Okay! I got started on the executive summary. Please take a look and add/edit however you'd like. For the record, here are my summarized points:

- Increasingly, open advocates feel empowered to lead initiatives and campaigns with deep social an ecological impacts, but they cannot do this without creating coalitions of participants acting with open organizational principles in mind.
- Collaborations between open communities and social impact-focused organizations often involve aims and goals different from those between for-profit or shareholder-driven organizations.
- Open advocates serve as "bridges" or liaisons between allied communities, projects, and initiatives.
- Open advocates succeed by finding common linguistic and value frameworks that unite seemingly disparate groups.
- Integrating open organizational principles into social impact-focused organizations helps advocates to place communities' needs and desires at the center of their work.
- Open advocates can build Architectures of Participation and Communication Ecosystems to align stakeholders on critical work.
- Setting strategy for newly formed open organizations forcused on social impacts involves sketching unifying principles, making effective connections between allies, and establishing clear structures.
- Stakeholders can share their mission, vision, and values statements to find points of critical overlap that might galvanize their work.
- Making connections with potential allies involves listening deeply and critical to others' needs.
- Organizational leaders tend to find comfort in structure, so open advocates can minimize the stress of change by document and making transparent their transformation plans.

**Comment by semioticrobotic** [comment]
Also, if @Hleson could please confirm edits to her bio, that'd be great.

Very close now!

**Comment by LauraHilliger** [comment]
Fantastic @semioticrobotic - I just rearranged one point and fixed a typo. THANK YOU!!

**Comment by semioticrobotic** [comment]
Awesome! Thank you for doing that, @LauraHilliger!

@Hleson received feedback from a colleague and has asked for some time to integrate it into the final document. When she is finished, I can help review, address anything you both feel needs addressing, and then get this into production.

**Comment by semioticrobotic** [comment]
Opened #8 and will continue pushing updates there. Please hop in if you'd like!

**Comment by semioticrobotic** [comment]
I was able to produce [an ePub prototype](https://github.com/open-organization/open-perspectives/blob/994d08cf80cd570ec8d4d8b584da7a10d9046096/opening-up-social-impact-focused-organizations/opening-up-social-impact-focused-organizations.epub?raw=true) today, and it's building splendidly! Useful, perhaps, for your next round of review.

**Comment by semioticrobotic** [comment]
And now we've got [a PDF prototype](https://raw.githubusercontent.com/open-organization/open-perspectives/d085eeda9ef74d7344dd8df70ded7a4971420da6/opening-up-social-impact-focused-organizations/opening-up-social-impact-focused-organizations.pdf)!

I have not yet had an opportunity to review, but please do take a look and send along any feedback or corrections you may have.

**Comment by LauraHilliger** [comment]
It looks amazing. Can we start sharing yet!? A little launch of some sort? IT LOOKS SO AWESOME AND THANK YOU BOTH AND I'M VERY HAPPY!

**Comment by semioticrobotic** [comment]
I'm so glad you're happy! Not ready for sharing just yet. Here's what we need to do to make that happen:

- Write a summary/promotional blurb (a short paragraph we use for the README and for promotional emails and tweets, etc.); see the placeholder in the README
- Perform final review of the PDF (check for inconsistencies, formatting errors, etc.)
- Choose a launch date
- Merge branch with `main`
- Send promotional messages, announcements, etc.

I'm largely away from my computer for the rest of the week but can try to get to some of this over the weekend!

**Comment by Hleson** [comment]
Dears this is so exciting. Amazing to see it in layout. ' your open advocate heart' - this should be a t-shirt or sticker :)

- Summary - happy to work on this with you both. Should we have a separate writing space?

- Final review of PDF - With apologies, I do have some minor edits: 
1. page 7 first paragraph
"Across the global, **International** Federation of Red Cross and Red Crescent Societies (IFRC), many products, services, and programs have included components supporting greater openness, but no specific strategy or policy documents mentioned open principles explicitly. One IFRC project started in 2016, the GO platform, utilized an open technology stack, building on the use of OpenDataKit and Kobo.1  (reason: there was an extra 'federated' in the 1st sentence)
 
Crafted for teams to learn about data literacy, **responsible data use*, and open collaboration, the IFRC Data Playbook is an extensive, collaboratively written toolkit.4 (reason: replaced 'open data' with 'responsible data use'. 

2. page 11 - we should give a citation for InnerSource networks - https://innersourcecommons.org/
3. There is no **one** network of civil society/humanitarian/tech organizations in open source. (Reason : there are networks but they don't often overlap. We state this later in the article, but best to be clear.)

- Launch date - Is it possible to do it before end of April?
- Merge- assuming this is a Bryan task
- Promotional messages - we should be mindful of a few occasions in April - Easter (Julian and Gregorian), Passover and Ramadan. As such we may need to work around these dates some. 

Many kind thanks and happy Sunday

**Comment by semioticrobotic** [comment]
Thanks for this, @Hleson! My first order of business with be making those text corrections so we've ensured we're working with the best version of the prose. I'll do that first, then return here with an update in other areas. Thanks!

**Comment by semioticrobotic** [comment]
Okay! Had some unexpected extra time this morning!

I [incorporated the changes](https://github.com/open-organization/open-perspectives/pull/8/commits/87365447007189ca280ef01925ac411c2dc61eea) from @Hleson. Then I created and pushed new [ePub](https://github.com/open-organization/open-perspectives/raw/87365447007189ca280ef01925ac411c2dc61eea/opening-up-social-impact-focused-organizations/opening-up-social-impact-focused-organizations.epub) and [PDF](https://raw.githubusercontent.com/open-organization/open-perspectives/87365447007189ca280ef01925ac411c2dc61eea/opening-up-social-impact-focused-organizations/opening-up-social-impact-focused-organizations.pdf) proofs. Please review if/when you like.

Meanwhile, I will start looking at the other items on our checklist.

**Comment by semioticrobotic** [comment]
Alrighty, @LauraHilliger and @Hleson: I've started putting together a few resources, including a summary blurb and release announcement. Please [take a look when you have a moment](https://notes.theopenorganization.org/KpEbWIlHTdCva__HXMnZjg#) and tweak away. I will be able to return to this tomorrow.

**Comment by LauraHilliger** [comment]
made a tiny tweak, but wasn't sure if you just wanted to pull bios from the paper or if you had something else in mind? In any case, it looks great. On launch date - is it possible this week or by Wed next? Would it be better to wait until after Easter and Passover? The week of 25th?

**Comment by semioticrobotic** [comment]
> made a tiny tweak, but wasn't sure if you just wanted to pull bios from the paper or if you had something else in mind?

Nothing else in mind! I was just going to pull from the paper itself (for sake of consistency). I can do that today as I finish the announcement.

In any case, it looks great. On launch date - is it possible this week or by Wed next? Would it be better to wait until after Easter and Passover? The week of 25th?

Given how relatively smoothly production is going, we can surely launch this week if that suits you both. I can finish production work in the next day or two and merge the branch in time for a Thursday (April 07) launch. Does that seem reasonable/appropriate?

**Comment by LauraHilliger** [comment]
YES!!!

**Comment by semioticrobotic** [comment]
Sounds great to me. Give me just a few hours to muddle through some meetings and then I can return to our checklist.

**Comment by Hleson** [comment]
Wonderful. April 7th is a great day!

What else do we need to prepare?

**Comment by LauraHilliger** [comment]
@semioticrobotic Just added it to the website (I guess it needs a minute to update), and I can't check your checkbox for some reason :/ but YAY!! Exciting

**Comment by semioticrobotic** [comment]
Looks perfect, @LauraHilliger. Big thanks for doing that.

We now have just about everything in place for a Thursday trumpet blast :postal_horn: :postal_horn: . Can use tomorrow to ensure we haven't missed anything Exciting indeed!

**Comment by LauraHilliger** [comment]
I have a LinkedIn post ready to go...literally sitting on my hands waiting for @semioticrobotic to wake up 🤣

**Comment by Hleson** [comment]
Time to wait : )  I guess we should have chatted about times. The  best window for global audiences is 11 am CEST - 2pm CEST.

**Comment by semioticrobotic** [comment]
I am indeed up! :yawning_face: Let's do this!

**Comment by LauraHilliger** [comment]
Linked in: https://www.linkedin.com/feed/update/urn:li:activity:6917798799012712449/

**Comment by Hleson** [comment]
@semioticrobotic  - thank you so much for your coaching, editing, and mentoring through this process. @LauraHilliger -gosh I am so proud of our efforts and learned so much from you. Thank you so much. Now - let's see what happens with this conversation next. : )

**Comment by semioticrobotic** [comment]
@LauraHilliger: Thank you! [Tweeted and pinned](https://twitter.com/openorgproject/status/1512036585243660293)!

@Hleson: My absolute privilege! Thanks for all your work on this important resource.

**Comment by LauraHilliger** [comment]
HUGE ADMIRATION for both of you @semioticrobotic and @hleson - wouldn't have gotten there without you both. I'm so proud, I even gave it a featured spot on my books page: https://www.laurahilliger.com/books/

We can probably close this ticket now!!

**Comment by Hleson** [comment]
Hey @semioticrobotic - it looks like the link on twitter is broken. May need to reshare

**Comment by semioticrobotic** [comment]
Roger that, @LauraHilliger! Closing up shop here. Once again: Great work and huge props to you both.
