### ISSUE TITLE
Definition of the word Board

### ISSUE THREAD

**Issue by JosGroenNL** [open-organization/open-perspectives#5]
I had a lively conversation with Delisa yesterday about the E-book. What
transpires is there where I speak of the board there is a difference how this is
interpreted in america and europe. Therefore, the proposal is to replace the
word board with executive team or management team throughout the text.

**Comment by semioticrobotic** [comment]
Paging @JosGroenNL! I've updated the language in this issue and invite your review of the changes before I typeset the revised text. Please see the [changes outlined here](https://github.com/open-organization/open-perspectives/commit/323375857499dabb25cd931c6e22f298ac03c66c) and let me know if all looks okay to you.

**Comment by JosGroenNL** [comment]
Can it be a foreword instead of preface?

**Comment by semioticrobotic** [comment]
Ah, yes! Of course. Thanks for that reminder. I'd forgotten your preface but can certainly change it.
